### ISSUE TITLE
oAuth App Authentication Support is missing

### ISSUE THREAD

**Issue by xSAVIKx** [pulumi/pulumi-pagerduty#569]
### Describe what happened

I'm trying to set up PagerDuty using the provider and trying to authenticate using oAuth app clientID + secret + subdomain. Unfortunately when I try doing so I get the following error every time:
```
    error: Cannot obtain plugin client:
    No valid credentials found for PagerDuty provider.
    Please see https://www.terraform.io/docs/providers/pagerduty/index.html
    for more information on providing credentials for this provider.
```

If I switch to token-based v2 auth everything works as expected.

### Sample program

Pulumi.yaml:
```
name: service-trains
runtime: yaml
description: PagerDuty bug
resources:
  pdProvider:
    type: pulumi:providers:pagerduty
    properties:
#      token: ${pagerduty:token}
      useAppOauthScopedToken:
        pdClientId: ${pagerduty:clientId}
        pdClientSecret: ${pagerduty:clientSecret}
        pdSubdomain: ${pagerduty:subdomain}
    options:
      version: 4.13.2
  devsUser:
    type: pagerduty:User
    properties:
      email: some-email@example.com
      name: Dev Team
      description: Development team
      jobTitle: Devs
      role: limited_user
    options:
      provider: ${pdProvider}
```

Pulumi.pagerduty.yaml:
```
config:
  pagerduty:clientId:
    secure: some-secret
  pagerduty:clientSecret:
    secure: some-secret
  pagerduty:subdomain: some-sub-domain
  pagerduty:token:
    secure: some-secret
  pulumi:disable-default-providers:
    - "*"
```

### Log output

Diagnostics:
  pagerduty:index:User (devsUser):
    error: Cannot obtain plugin client:
    No valid credentials found for PagerDuty provider.
    Please see https://www.terraform.io/docs/providers/pagerduty/index.html
    for more information on providing credentials for this provider.

### Affected Resource(s)

pagerduty:User

### Output of `pulumi about`

pulumi about
CLI          
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME  VERSION
language  yaml  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml

Current Stack: CURRENT_STACK

TYPE                          URN
<STACKS>

Found no pending operations associated with travelshift/pagerduty

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xSAVIKx
User           xSAVIKx
Organizations  <ORGS>
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
